trigger:
  branches:
    include:
      - testen
  # tags:
  #   include:
  #     - release-v*

pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MamsInfra
      type: git
      name: MijnAmsterdam/mijn-amsterdam-infra
      ref: refs/heads/pipeline-fe

parameters:
  - name: btdBuild
    type: boolean
    default: true
  - name: btdTest
    type: boolean
    default: true
  - name: btdDeploy
    type: boolean
    default: true

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'testen') }}:
      - group: MAPipelineVariables-t
      - name: dtapName
        value: t
  - name: dockerImageName
    value: mams-wpi
  - name: dockerImage
    value: $(dockerACRUrl)/${{ variables.dockerImageName }}

jobs:
  - template: pipelines/jobs/apps/btd-koppel-api.yaml@MamsInfra
    parameters:
      serviceConnectionName: $(serviceConnectionName)
      appServiceName: $(appServiceNameWPI)
      dockerImageName: ${{ variables.dockerImageName }}
      dockerImage: $(dockerACRUrl)/${{ variables.dockerImageName }}
      dtapName: ${{ variables.dtapName }}
      btdBuild: ${{ parameters.btdBuild }}
      btdTest: ${{ parameters.btdTest }}
      btdDeploy: ${{ parameters.btdDeploy }}
