trigger:
  branches:
    include:
      - testen
  # tags:
  #   include:
  #     - release-v*

pr:
  branches:
    include:
      - main

resources:
  repositories:
    - repository: MamsInfra
      type: git
      name: MijnAmsterdam/mijn-amsterdam-infra
      ref: refs/heads/pipeline-fe

parameters:
  - name: Build
    type: boolean
    default: true
  - name: Test
    type: boolean
    default: true
  - name: Deploy
    type: boolean
    default: true

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'ontwikkelen') }}:
      - group: MAPipelineVariables-o
  - name: dockerImageName
    value: mams-wpi
  - name: dockerImage
    value: $(dockerACRUrl)/$(variables.dockerImageName)

stages:
  - ${{ if eq(parameters.Build, true) }}:
      - template: pipelines/stages/build-koppel-api.yaml@MamsInfra
        parameters:
          serviceConnectionName: $(serviceConnectionName)
          adoEnvironment: $(adoEnvironment)
          dockerImage: $(dockerImage)

  - ${{ if eq(parameters.Test, true) }}:
      - template: pipelines/stages/test-koppel-api.yaml@MamsInfra
        parameters:
          adoEnvironment: $(adoEnvironment)
          dockerImage: $(dockerImage)

  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), eq(parameters.Deploy, true)) }}:
      - template: pipelines/stages/deploy-koppel-api.yaml@MamsInfra
        parameters:
          serviceConnectionName: $(serviceConnectionName)
          adoEnvironment: $(adoEnvironment)
          appServiceName: $(appServiceNameWPI)
          dockerImageName: $(dockerImageName)
          dockerImage: $(dockerImage)
