E_AANVRAAG_PRODUCT_NAMES = [
    "Tozo 1",
    "Tozo 2",
    "Tozo 3",
    "Tozo 4",
    "Tozo 5",
    "TONK",
    "bbz",
]

TOZO_PRODUCT_TITLES = [
    "Tozo 1 (aangevraagd voor 1 juni 2020)",
    "Tozo 2 (aangevraagd vanaf 1 juni 2020)",
    "Tozo 3 (aangevraagd vanaf 1 oktober 2020)",
    "Tozo 4 (aangevraagd vanaf 1 april 2021)",
    "Tozo 5 (aangevraagd vanaf 1 juli 2021)",
]

E_AANVRAAG_DOCUMENT_CONFIG = {
    # Tozo 1
    "756": {
        "omschrijving": "Verkorte Aanvraag BBZ",
        # "labels": aanvraagLabels,
        "document_title": "Ontvangst- bevestiging Aanvraag",
        "product": "Tozo 1",
        "step_type": "aanvraag",
    },
    "770": {
        "omschrijving": "Tegemoetkoming Ondernemers en Zelfstandigen",
        # "labels": aanvraagLabels,
        "document_title": "Ontvangst- bevestiging Aanvraag",
        "product": "Tozo 1",
        "step_type": "aanvraag",
    },
    "175296": {
        "omschrijving": "Toekennen voorschot Tozo",
        # "labels": voorschotToekennenLabels,
        "document_title": "Brief betaling voorschot",
        "product": "Tozo 1",
        "step_type": "voorschot",
    },
    "175299": {
        "omschrijving": "Bbz Toekennen voorschot Tozo via batch",
        # "labels": voorschotToekennenLabels,
        "document_title": "Brief betaling voorschot",
        "product": "Tozo 1",
        "step_type": "voorschot",
    },
    "175303": {
        "omschrijving": "Tozo Toekennen",
        # "labels": toekennenLabels,
        "document_title": "Besluit toekenning uitkering",
        "product": "Tozo 1",
        "product_specific": "uitkering",
        "step_type": "besluit",
        "decision": "toekenning",
    },
    "175304": {
        "omschrijving": "Tozo Afwijzen",
        # "labels": afwijzenLabels,
        "document_title": "Besluit afwijzing",
        "product": "Tozo 1",
        "step_type": "besluit",
        "decision": "afwijzing",
    },
    "175305": {
        "omschrijving": "Tozo Buiten behandeling laten",
        # "labels": buitenBehandelingLabels,
        "document_title": "Besluit buiten behandeling",
        "product": "Tozo 1",
        "step_type": "besluit",
        "decision": "buitenbehandeling",
    },
    "175306": {
        "omschrijving": "Tozo Hersteltermijn",
        # "labels": herstelTermijnLabels,
        "document_title": "Brief meer informatie",
        "product": "Tozo 1",
        "step_type": "herstelTermijn",
    },
    "175308": {
        "omschrijving": "Tozo Terugvordering voorschot",
        # "labels": afwijzenLabels,
        "document_title": "Besluit afwijzing",
        "product": "Tozo 1",
        "step_type": "besluit",
        "decision": "afwijzing",
    },
    "175311": {
        "omschrijving": "Tozo Toekennen bedrijfskapitaal",
        # "labels": toekennenLabels,
        "document_title": "Besluit toekenning lening",
        "product": "Tozo 1",
        "product_specific": "lening",
        "step_type": "besluit",
        "decision": "toekenning",
    },
    "175314": {
        "omschrijving": "Tozo Toekennen via batch",
        # "labels": toekennenLabels,
        "document_title": "Besluit toekenning uitkering",
        "product": "Tozo 1",
        "product_specific": "uitkering",
        "step_type": "besluit",
        "decision": "toekenning",
    },
    "175317": {
        "omschrijving": "Tozo Intrekken met terugvordering voorschot",
        # "labels": intrekkenLabels,
        "document_title": "Besluit intrekking met terugbetaling",
        "product": "Tozo 1",
        "step_type": "besluit",
        "decision": "intrekking",
    },
    "175331": {
        "omschrijving": "Tozo Intrekken",
        # "labels": intrekkenLabels,
        "document_title": "Brief intrekking aanvraag",
        "product": "Tozo 1",
        "step_type": "besluit",
        "decision": "intrekking",
    },
    "175334": {
        "omschrijving": "Tozo Vrije beschikking",
        # "labels": vrijeBeschikkingLabels,
        "document_title": "Besluit Tozo 1 aanvraag",
        "product": "Tozo 1",
        "step_type": "besluit",
        "decision": "toekenning",
    },
    "175335": {
        "omschrijving": "Tozo Afwijzen via batch",
        # "labels": afwijzenLabels,
        "document_title": "Besluit afwijzing",
        "product": "Tozo 1",
        "step_type": "besluit",
        "decision": "afwijzing",
    },
    # TOZO 2
    "777": {
        "omschrijving": "TOZO 2 (vervolgregeling tegemoetkoming Ondernemers en Zelfstandigen)",
        # "labels": aanvraagLabels,
        "document_title": "Ontvangst- bevestiging Aanvraag",
        "product": "Tozo 2",
        "step_type": "aanvraag",
    },
    "175336": {
        "omschrijving": "Tozo2 Toekennen",
        # "labels": toekennenLabels,
        "document_title": "Besluit toekenning uitkering",
        "product": "Tozo 2",
        "product_specific": "uitkering",
        "step_type": "besluit",
        "decision": "toekenning",
    },
    "175337": {
        "omschrijving": "Tozo2 Afwijzen",
        # "labels": afwijzenLabels,
        "document_title": "Besluit afwijzing",
        "product": "Tozo 2",
        "step_type": "besluit",
        "decision": "afwijzing",
    },
    "175338": {
        "omschrijving": "Tozo2 Toekennen bedrijfskapitaal",
        # "labels": toekennenLabels,
        "document_title": "Besluit toekenning lening",
        "product": "Tozo 2",
        "product_specific": "lening",
        "step_type": "besluit",
        "decision": "toekenning",
    },
    "175340": {
        "omschrijving": "Tozo2 Hersteltermijn",
        # "labels": herstelTermijnLabels,
        "document_title": "Brief meer informatie",
        "product": "Tozo 2",
        "step_type": "herstelTermijn",
    },
    "175341": {
        "omschrijving": "Tozo2 Intrekken",
        # "labels": intrekkenLabels,
        "document_title": "Brief intrekking aanvraag",
        "product": "Tozo 2",
        "step_type": "besluit",
        "decision": "intrekking",
    },
    "175342": {
        "omschrijving": "Tozo2 Buiten behandeling laten",
        # "labels": buitenBehandelingLabels,
        "document_title": "Besluit buiten behandeling",
        "product": "Tozo 2",
        "step_type": "besluit",
        "decision": "buitenbehandeling",
    },
    "175343": {
        "omschrijving": "Tozo2 Terugvordering voorschot",
        # "labels": afwijzenLabels,
        "document_title": "Besluit terugvordering",
        "product": "Tozo 2",
        "step_type": "besluit",
        "decision": "intrekking",
    },
    "175344": {
        "omschrijving": "Tozo2 Intrekken met terugvordering voorschot",
        # "labels": intrekkenLabels,
        "document_title": "Besluit intrekking met terugbetaling",
        "product": "Tozo 2",
        "step_type": "besluit",
        "decision": "intrekking",
    },
    "175345": {
        "omschrijving": "Tozo2 Toekennen voorschot via batch",
        # "labels": voorschotToekennenLabels,
        "document_title": "Brief betaling voorschot",
        "product": "Tozo 2",
        "step_type": "voorschot",
    },
    "175346": {
        "omschrijving": "Tozo2 Toekennen voorschot",
        # "labels": voorschotToekennenLabels,
        "document_title": "Brief betaling voorschot",
        "product": "Tozo 2",
        "step_type": "voorschot",
    },
    "175347": {
        "omschrijving": "Tozo2 Toekennen via batch",
        # "labels": toekennenLabels,
        "document_title": "Besluit toekenning uitkering",
        "product": "Tozo 2",
        "product_specific": "uitkering",
        "step_type": "besluit",
        "decision": "toekenning",
    },
    "175359": {
        "omschrijving": "Tozo2 Afwijzen via batch",
        # "labels": afwijzenLabels,
        "document_title": "Besluit afwijzing",
        "product": "Tozo 2",
        "step_type": "besluit",
        "decision": "afwijzing",
    },
    # Na besluit
    "790": {
        "omschrijving": "Tozo 2 inkomstenwijziging",
        "document_title": "Wijziging inkomsten",
        "step_type": "verklaring",
        # "labels": inkomstenVerklaringLabels,
        "product": "Tozo 2",
    },
    "175650": {
        "omschrijving": "Tozo 2 Terugvorderingsbesluit",
        "document_title": "Besluit terugvordering",
        "step_type": "besluit",
        # "labels": terugvorderingLabels,
        "product": "Tozo 2",
        "product_specific": "uitkering",
        "decision": "toekenning",
    },
    "175645": {
        "omschrijving": "Tozo 2 Terugvorderingsbesluit",
        "document_title": "Besluit terugvordering",
        "step_type": "besluit",
        # "labels": terugvorderingLabels,
        "product": "Tozo 2",
        "product_specific": "uitkering",
        "decision": "toekenning",
    },
    # TOZO 3
    "785": {
        "omschrijving": "TOZO 3 (vervolgregeling tegemoetkoming Ondernemers en Zelfstandigen)",
        # "labels": aanvraagLabels,
        "document_title": "Ontvangst- bevestiging Aanvraag",
        "product": "Tozo 3",
        "step_type": "aanvraag",
    },
    "175309": {
        "omschrijving": "Tozo3 Toekennen",
        "step_type": "besluit",
        # "labels": toekennenLabels,
        "product": "Tozo 3",
        "product_specific": "uitkering",
        "document_title": "Besluit toekenning uitkering",
    },
    "175307": {
        "omschrijving": "Tozo3 Toekennen voorschot",
        "step_type": "voorschot",
        # "labels": voorschotToekennenLabels,
        "product": "Tozo 3",
        "document_title": "Brief betaling voorschot",
    },
    "175310": {
        "omschrijving": "Tozo3 Hersteltermijn",
        "step_type": "herstelTermijn",
        # "labels": herstelTermijnLabels,
        "product": "Tozo 3",
        "document_title": "Brief meer informatie",
    },
    "175357": {
        "omschrijving": "Tozo3 Toekennen via batch",
        "step_type": "besluit",
        # "labels": toekennenLabels,
        "product": "Tozo 3",
        "product_specific": "uitkering",
        "document_title": "Besluit toekenning uitkering",
        "decision": "toekenning",
    },
    "175358": {
        "omschrijving": "Tozo3 Buiten behandeling laten",
        "step_type": "besluit",
        # "labels": buitenBehandelingLabels,
        "product": "Tozo 3",
        "document_title": "Besluit buiten behandeling",
        "decision": "buitenbehandeling",
    },
    "175364": {
        "omschrijving": "Tozo3 Afwijzen",
        "step_type": "besluit",
        # "labels": afwijzenLabels,
        "product": "Tozo 3",
        "document_title": "Besluit afwijzing",
        "decision": "afwijzing",
    },
    "175367": {
        "omschrijving": "Tozo3 Intrekken met terugvordering voorschot",
        "step_type": "besluit",
        # "labels": intrekkenLabels,
        "product": "Tozo 3",
        "document_title": "Besluit intrekking met terugbetaling",
        "decision": "intrekking",
    },
    "175368": {
        "omschrijving": "Tozo3 Terugvordering voorschot",
        "step_type": "besluit",
        # "labels": afwijzenLabels,
        "product": "Tozo 3",
        "document_title": "Besluit terugvordering",
        "decision": "intrekking",
    },
    "175369": {
        "omschrijving": "Tozo3 Toekennen bedrijfskapitaal",
        "step_type": "besluit",
        # "labels": toekennenLabels,
        "product": "Tozo 3",
        "product_specific": "lening",
        "document_title": "Besluit toekenning lening",
        "decision": "toekenning",
    },
    "175370": {
        "omschrijving": "Tozo3 Intrekken",
        "step_type": "besluit",
        # "labels": intrekkenLabels,
        "product": "Tozo 3",
        "document_title": "Brief intrekking aanvraag",
        "decision": "intrekking",
    },
    "175371": {
        "omschrijving": "Tozo3 Afwijzen via batch",
        "step_type": "besluit",
        # "labels": afwijzenLabels,
        "product": "Tozo 3",
        "document_title": "Besluit afwijzing",
        "decision": "afwijzing",
    },
    "175372": {
        "omschrijving": "Tozo3 Toekennen voorschot via batch",
        "step_type": "voorschot",
        # "labels": voorschotToekennenLabels,
        "product": "Tozo 3",
        "document_title": "Brief betaling voorschot",
    },
    # Na besluit
    "792": {
        "omschrijving": "Tozo 3 inkomstenwijziging",
        "document_title": "Wijziging inkomsten",
        "step_type": "verklaring",
        # "labels": inkomstenVerklaringLabels,
        "product": "Tozo 3",
    },
    "1725650": {
        "omschrijving": "Tozo 3 Terugvorderingsbesluit",
        "document_title": "Besluit terugvordering",
        "step_type": "besluit",
        # "labels": terugvorderingLabels,
        "product": "Tozo 3",
        "product_specific": "uitkering",
        "decision": "intrekking",
    },
    "1725645": {
        "omschrijving": "Tozo 3 Terugvorderingsbesluit",
        "document_title": "Besluit terugvordering",
        "step_type": "besluit",
        # "labels": terugvorderingLabels,
        "product": "Tozo 3",
        "product_specific": "uitkering",
        "decision": "intrekking",
    },
    # TOZO 4
    "800": {
        "omschrijving": "Tozo 4 (vervolgregeling tegemoetkoming Ondernemers en Zelfstandigen)",
        "document_title": "Ontvangst- bevestiging Aanvraag",
        "step_type": "aanvraag",
        # "labels": aanvraagLabels,
        "product": "Tozo 4",
    },
    "175654": {
        "omschrijving": "Tozo 4 Toekennen",
        "document_title": "Besluit toekenning uitkering",
        "step_type": "besluit",
        # "labels": toekennenLabels,
        "product": "Tozo 4",
        "product_specific": "uitkering",
        "decision": "toekenning",
    },
    "175651": {
        "omschrijving": "Tozo 4 Afwijzen",
        "document_title": "Besluit afwijzing",
        "step_type": "besluit",
        # "labels": afwijzenLabels,
        "product": "Tozo 4",
        "decision": "afwijzing",
    },
    "175673": {
        "omschrijving": "Tozo 4 Afwijzen via batch",
        "document_title": "Besluit afwijzing",
        "step_type": "besluit",
        # "labels": afwijzenLabels,
        "product": "Tozo 4",
        "decision": "afwijzing",
    },
    "175656": {
        "omschrijving": "Tozo 4 Toekennen bedrijfskapitaal",
        "document_title": "Besluit toekenning lening",
        "step_type": "besluit",
        # "labels": toekennenLabels,
        "product": "Tozo 4",
        "product_specific": "lening",
        "decision": "toekenning",
    },
    "175689": {
        "omschrijving": "Tozo 4 Hersteltermijn",
        "document_title": "Brief meer informatie",
        "step_type": "herstelTermijn",
        # "labels": herstelTermijnLabels,
        "product": "Tozo 4",
    },
    "175670": {
        "omschrijving": "Tozo 4 Intrekken",
        "document_title": "Brief intrekking aanvraag",
        "step_type": "besluit",
        # "labels": intrekkenLabels,
        "product": "Tozo 4",
        "decision": "intrekking",
    },
    "175652": {
        "omschrijving": "Tozo 4 Buiten behandeling laten",
        "document_title": "Besluit buiten behandeling",
        "step_type": "besluit",
        # "labels": buitenBehandelingLabels,
        "product": "Tozo 4",
        "decision": "buitenbehandeling",
    },
    "175677": {
        "omschrijving": "Tozo 4 Toekennen voorschot via batch",
        "document_title": "Brief betaling voorschot",
        "step_type": "voorschot",
        # "labels": voorschotToekennenLabels,
        "product": "Tozo 4",
        "decision": "toekenning",
    },
    "175657": {
        "omschrijving": "Tozo 4 Toekennen voorschot",
        "document_title": "Brief betaling voorschot",
        "step_type": "voorschot",
        # "labels": voorschotToekennenLabels,
        "product": "Tozo 4",
        "decision": "toekenning",
    },
    "175674": {
        "omschrijving": "Tozo 4 Toekennen via batch",
        "document_title": "Besluit toekenning uitkering",
        "step_type": "besluit",
        # "labels": toekennenLabels,
        "product": "Tozo 4",
        "product_specific": "uitkering",
        "decision": "toekenning",
    },
    # Na besluit
    "794": {
        "omschrijving": "Tozo 4 inkomstenwijziging",
        "document_title": "Wijziging inkomsten",
        "step_type": "verklaring",
        # "labels": inkomstenVerklaringLabels,
        "product": "Tozo 4",
    },
    "1735650": {
        "omschrijving": "Tozo 4 Terugvorderingsbesluit",
        "document_title": "Besluit terugvordering",
        "step_type": "besluit",
        # "labels": terugvorderingLabels,
        "product": "Tozo 4",
        "product_specific": "uitkering",
        "decision": "intrekking",
    },
    "1735645": {
        "omschrijving": "Tozo 4 Terugvorderingsbesluit",
        "document_title": "Besluit terugvordering",
        "step_type": "besluit",
        # "labels": terugvorderingLabels,
        "product": "Tozo 4",
        "product_specific": "uitkering",
        "decision": "intrekking",
    },
    # Tozo 5
    "837": {
        "omschrijving": "Tozo 5 (vervolgregeling tegemoetkoming Ondernemers en Zelfstandigen)",
        "document_title": "Ontvangst- bevestiging Aanvraag",
        "step_type": "aanvraag",
        # "labels": aanvraagLabels,
        "product": "Tozo 5",
    },
    "176167": {
        "omschrijving": "Tozo5 Toekennen",
        "document_title": "Besluit toekenning uitkering",
        "step_type": "besluit",
        # "labels": toekennenLabels,
        "product": "Tozo 5",
        "product_specific": "uitkering",
        "decision": "toekenning",
    },
    "176165": {
        "omschrijving": "Tozo5 Afwijzen",
        "document_title": "Besluit afwijzing",
        "step_type": "besluit",
        # "labels": afwijzenLabels,
        "product": "Tozo 5",
        "decision": "afwijzing",
    },
    "176169": {
        "omschrijving": "Tozo5 Afwijzen via batch",
        "document_title": "Besluit afwijzing",
        "step_type": "besluit",
        # "labels": afwijzenLabels,
        "product": "Tozo 5",
        "decision": "afwijzing",
    },
    "176168": {
        "omschrijving": "Tozo5 Toekennen bedrijfskapitaal",
        "document_title": "Besluit toekenning lening",
        "step_type": "besluit",
        # "labels": toekennenLabels,
        "product": "Tozo 5",
        "product_specific": "lening",
        "decision": "toekenning",
    },
    "176164": {
        "omschrijving": "Tozo5 Hersteltermijn",
        "document_title": "Brief meer informatie",
        "step_type": "herstelTermijn",
        # "labels": herstelTermijnLabels,
        "product": "Tozo 5",
    },
    "176163": {
        "omschrijving": "Tozo5 Intrekken",
        "document_title": "Brief intrekking aanvraag",
        "step_type": "besluit",
        # "labels": intrekkenLabels,
        "product": "Tozo 5",
        "decision": "intrekking",
    },
    "176166": {
        "omschrijving": "Tozo5 Buiten behandeling laten",
        "document_title": "Besluit buiten behandeling",
        "step_type": "besluit",
        # "labels": buitenBehandelingLabels,
        "product": "Tozo 5",
        "decision": "buitenbehandeling",
    },
    "176170": {
        "omschrijving": "Tozo5 Toekennen via batch",
        "document_title": "Besluit toekenning uitkering",
        "step_type": "besluit",
        # "labels": toekennenLabels,
        "product": "Tozo 5",
        "product_specific": "uitkering",
        "decision": "toekenning",
    },
    "176171": {
        "omschrijving": "Tozo5 Toekennen voorschot via batch",
        "document_title": "Brief betaling voorschot",
        "step_type": "voorschot",
        # "labels": voorschotToekennenLabels,
        "product": "Tozo 5",
    },
    "1725657": {
        "omschrijving": "Tozo5 Toekennen voorschot",
        "document_title": "Brief betaling voorschot",
        "step_type": "voorschot",
        # "labels": voorschotToekennenLabels,
        "product": "Tozo 5",
    },
    # Na besluit
    "1745650": {
        "omschrijving": "Tozo5 Terugvorderen na inkomstenopgave",
        "document_title": "Besluit terugvordering",
        "step_type": "besluit",
        # "labels": terugvorderingLabels,
        "product": "Tozo 5",
        "product_specific": "uitkering",
        "decision": "intrekking",
    },
    "1745645": {
        "omschrijving": "Tozo5 Terugvorderen na inkomstenopgave (batch)",
        "document_title": "Besluit terugvordering",
        "step_type": "besluit",
        # "labels": terugvorderingLabels,
        "product": "Tozo 5",
        "product_specific": "uitkering",
        "decision": "intrekking",
    },
    "838": {
        "omschrijving": "Tozo 5 inkomstenwijziging",
        "document_title": "Wijziging inkomsten",
        "step_type": "verklaring",
        # "labels": inkomstenVerklaringLabels,
        "product": "Tozo 5",
    },
    # TONK
    "802": {
        "omschrijving": "TONK aanvraag",
        # "labels": aanvraagLabels,
        "documentTitle": "Aanvraag TONK",
        "product": "TONK",
        "stepType": "aanvraag",
        "productSpecific": "uitkering",
    },
    "176137": {
        "omschrijving": "TONK hersteltermijn",
        # "labels": herstelTermijnLabels,
        "documentTitle": "Brief meer informatie",
        "product": "TONK",
        "stepType": "herstelTermijn",
        "productSpecific": "uitkering",
    },
    "176138": {
        "omschrijving": "TONK intrekken",
        # "labels": intrekkenLabels,
        "documentTitle": "Brief intrekking TONK aanvraag",
        "product": "TONK",
        "stepType": "besluit",
        "productSpecific": "uitkering",
        "decision": "intrekking",
    },
    "176149": {
        "omschrijving": "TONK toekennen",
        # "labels": toekennenLabels,
        "documentTitle": "Besluit toekenning uitkering",
        "product": "TONK",
        "stepType": "besluit",
        "productSpecific": "uitkering",
        "decision": "toekenning",
    },
    "176156": {
        "omschrijving": "TONK toekennen via batch",
        # "labels": toekennenLabels,
        "documentTitle": "Besluit toekenning uitkering",
        "product": "TONK",
        "stepType": "besluit",
        "productSpecific": "uitkering",
        "decision": "toekenning",
    },
    "176145": {
        "omschrijving": "TONK afwijzen",
        # "labels": afwijzenLabels,
        "documentTitle": "Besluit afwijzing",
        "product": "TONK",
        "stepType": "besluit",
        "productSpecific": "uitkering",
        "decision": "afwijzing",
    },
    "176155": {
        "omschrijving": "TONK afwijzen via batch",
        # "labels": afwijzenLabels,
        "documentTitle": "Besluit afwijzing",
        "product": "TONK",
        "stepType": "besluit",
        "productSpecific": "uitkering",
        "decision": "afwijzing",
    },
    "176146": {
        "omschrijving": "TONK Buiten behandeling laten",
        # "labels": buitenBehandelingLabels,
        "documentTitle": "Besluit buiten behandeling",
        "product": "TONK",
        "productSpecific": "uitkering",
        "stepType": "besluit",
        "decision": "buitenbehandeling",
    },
    "176180": {
        "omschrijving": "TONK Ambtshalve verlenging via batch",
        # "labels": verlengingLabels,
        "documentTitle": "Besluit verlenging",
        "product": "TONK",
        "productSpecific": "uitkering",
        "stepType": "besluit",
        "decision": "toekenning",
    },
    "176182": {
        "omschrijving": "TONK Besluit over verlenging",
        # "labels": besluitVerlengingLabels,
        "documentTitle": "Besluit over verlenging",
        "product": "TONK",
        "productSpecific": "uitkering",
        "stepType": "besluit",
        "decision": "toekenning",
    },
    "1726182": {
        "omschrijving": "TONK Bevestigen weigering verlenging",
        # "labels": weigeringVerlengingLabels,
        "documentTitle": "Brief bevestiging weigering",
        "product": "TONK",
        "productSpecific": "uitkering",
        "stepType": "besluit",
        "decision": "afwijzing",
    },
    "843": {
        "omschrijving": "Correctiemail Tonk",
        # "labels": correctieMailLabels,
        "documentTitle": "Mail verkeerde TONK-brief",
        "product": "TONK",
        "productSpecific": "uitkering",
        "stepType": "correctiemail",
        "datePublished": "2021-07-15T00:00:00+01:00",
    },
    # BBZ
    "844": {
        "omschrijving": "Bbz aanvraag",
        # "labels": aanvraagLabels,
        "documentTitle": "Aanvraag Bbz",
        "product": "Bbz",
        "stepType": "aanvraag",
    },
    "176195": {
        "omschrijving": "Transitie Bbz Toekennen batch",
        # "labels": toekennenLabels,
        "documentTitle": "Besluit toekenning uitkering",
        "product": "Bbz",
        "stepType": "besluit",
        "productSpecific": "uitkering",
        "decision": "toekenning",
    },
    "175843": {
        "omschrijving": "Bbz toekenning bedrijfskapitaal",
        # "labels": toekennenLabels,
        "documentTitle": "Besluit toekenning lening",
        "product": "Bbz",
        "stepType": "besluit",
        "productSpecific": "lening",
        "decision": "toekenning",
    },
    "175855": {
        "omschrijving": "Bbz verlenging beslistermijn met 13 weken",
        # "labels": meerTijdLabels,
        "documentTitle": "Brief verlenging beslistermijn",
        "product": "Bbz",
        "stepType": "beslistermijn",
    },
    "176351": {
        "omschrijving": "Transitie Bbz Hersteltermijn",
        # "labels": herstelTermijnLabels,
        "documentTitle": "Brief verzoek om meer informatie",
        "product": "Bbz",
        "stepType": "herstelTermijn",
    },
    "176368": {
        "omschrijving": "Brief aanvraag adviesrapport",
        # "labels": briefAdviesRapportLabels,
        "documentTitle": "Brief aanvraag adviesrapport",
        "product": "Bbz",
        "stepType": "brief",
    },
    "176350": {
        "omschrijving": "Transitie Bbz Intrekken",
        # "labels": intrekkenLabels,
        "documentTitle": "Brief intrekken Bbz aanvraag",
        "product": "Bbz",
        "stepType": "besluit",
        "decision": "intrekking",
    },
    "176353": {
        "omschrijving": "Transitie Bbz buiten behandeling stellen",
        # "labels": buitenBehandelingLabels,
        "documentTitle": "Besluit buiten behandeling",
        "product": "Bbz",
        "stepType": "besluit",
        "decision": "buitenbehandeling",
    },
    "175884": {
        "omschrijving": "Bbz akte bedrijfskapitaal",
        # "labels": akteLabels,
        "documentTitle": "Brief akte bedrijfskapitaal",
        "product": "Bbz",
        "stepType": "brief",
    },
    "176196": {
        "omschrijving": "Transitie Bbz voorschot toekennen batch",
        # "labels": voorschotLabels,
        "documentTitle": "Brief betaling voorschot",
        "product": "Bbz",
        "stepType": "voorschot",
        "decision": "toekenning",
    },
    "176197": {
        "omschrijving": "Transitie Bbz voorschot toekennen handmatig",
        # "labels": voorschotLabels,
        "documentTitle": "Brief betaling voorschot",
        "product": "Bbz",
        "stepType": "voorschot",
        "decision": "toekenning",
    },
    "176198": {
        "omschrijving": "Transitie Bbz Afwijzen",
        # "labels": afwijzenLabels,
        "documentTitle": "Besluit afwijzing",
        "product": "Bbz",
        "stepType": "besluit",
        "decision": "afwijzing",
    },
    "176194": {
        "omschrijving": "Transitie Bbz Toekennen handmatig",
        # "labels": toekennenLabels,
        "documentTitle": "Besluit toekenning uitkering",
        "product": "Bbz",
        "productSpecific": "uitkering",
        "stepType": "besluit",
        "decision": "toekenning",
    },
    "176301": {
        "omschrijving": "Ioaz Toekenning voorlopige uitkering",
        # "labels": toekennenVoorlopigLabels,
        "documentTitle": "Besluit toekenning",
        "product": "IOAZ",
        "stepType": "besluit",
        "decision": "toekenning",
    },
    "176322": {
        "omschrijving": "Ioaz Aanvraag hersteltermijn",
        # "labels": herstelTermijnLabels,
        "documentTitle": "Brief verzoek om meer informatie",
        "product": "IOAZ",
        "stepType": "herstelTermijn",
    },
    "176332": {
        "omschrijving": "Ioaz aanvraag buiten behandeling stellen",
        # "labels": buitenBehandelingLabels,
        "documentTitle": "Besluit buiten behandeling",
        "product": "IOAZ",
        "stepType": "besluit",
        "decision": "buitenbehandeling",
    },
    "1736301": {
        "omschrijving": "Ioaz Toekenning voorlopige uitkering",
        # "labels": toekennenVoorlopigLabels,
        "documentTitle": "Besluit toekenning",
        "product": "IOAZ",
        "stepType": "besluit",
        "decision": "toekenning",
    },
    "1736302": {
        "omschrijving": "Ioaz Toekenning definitieve uitkering",
        # "labels": toekennenLabels,
        "documentTitle": "Besluit toekenning uitkering",
        "product": "IOAZ",
        "productSpecific": "uitkering",
        "stepType": "besluit",
        "decision": "toekenning",
    },
    "1736303": {
        "omschrijving": "Ioaz afwijzing uitkering",
        # "labels": afwijzenLabels,
        "documentTitle": "Besluit afwijzing",
        "product": "IOAZ",
        "productSpecific": "uitkering",
        "stepType": "besluit",
        "decision": "afwijzing",
    },
    "851": {
        "omschrijving": "BBZ2 Inkomsten Verklaring",
        "documentTitle": "Wijziging inkomsten Bbz",
        "stepType": "verklaring",
        # "labels": inkomstenVerklaringLabels,
        "product": "Bbz",
        "decision": "afwijzing",
    },
    "176363": {
        "omschrijving": "Transitie Bbz Terugvordering via batch",
        "documentTitle": "Besluit terugvordering",
        "stepType": "besluit",
        # "labels": terugvorderingLabels,
        "product": "Bbz",
        "productSpecific": "uitkering",
        "decision": "toekenning",
    },
    "176364": {
        "omschrijving": "Transitie Bbz Terugvordering",
        "documentTitle": "Besluit terugvordering",
        "stepType": "besluit",
        # "labels": terugvorderingLabels,
        "product": "Bbz",
        "productSpecific": "uitkering",
        "decision": "toekenning",
    },
}
