openapi: 3.0.3
info:
  title: Focus API
  description: Koppel api tussen WPI (Focus) en Mijn Amsterdam
  version: 2.0.0
paths:
  /status/health:
    get:
      description: returns "OK" if api is running
      responses:
        "200":
          description: Returns "OK"
          content:
            application/json:
              schema:
                type: string
                enum:
                  - "OK"

    get:
      description: Returns a list aanvragen.
      parameters:
        - name: Authorization
          in: header
          description: Bearer token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    $ref: "#/components/schemas/Aanvragen"
                  status:
                    type: string
                    enum:
                      - "OK"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /wpi/e-aanvragen:
    get:
      description: Returns a list of E-aanvragen (Tozo, Tonk, Bbz).
      parameters:
        - name: Authorization
          in: header
          description: Bearer token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    $ref: "#/components/schemas/Aanvragen"
                  status:
                    type: string
                    enum:
                      - "OK"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /wpi/document:
    get:
      description: Geeft een bij een aanvraag behorend document terug voor een bepaalde persoon geidentificeerd door een BSN nummer
      parameters:
        - name: id
          in: query
          description: document id
          required: true
          schema:
            type: string
        - name: isBulk
          in: query
          description: Tells if the document is a bulk document
          schema:
            type: string
        - name: isDms
          in: query
          description: Tells if the document is a DMS (Document Management System) document
          schema:
            type: string
        - name: Authorization
          in: header
          description: Bearer token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: |
            Document contents (base64 encoded string), filename and description
            - description
            Short description of the document (normally null)
            - fileName
            Name of the file, including extension, e.g. doc.pdf
            - contents
            Base64 encoded contents
            - mime_type
            MIME type (application/pdf voor pdf documenten, anders application/octet-stream)
          content:
            application/pdf:
              schema:
                type: string
                format: binary
            application/octet-stream:
              schema:
                type: string
                format: binary
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /wpi/uitkering/specificaties-en-jaaropgaven:
    get:
      description: Returns a list uitkeringsspecificatie en jaaropgaven.
      parameters:
        - name: Authorization
          in: header
          description: Bearer token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    properties:
                      jaaropgaven:
                        type: array
                        items:
                          $ref: "#/components/schemas/Specificatie"
                      uitkeringsspecificaties:
                        type: array
                        items:
                          $ref: "#/components/schemas/Specificatie"
                  status:
                    type: string
                    enum:
                      - "OK"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Aanvragen:
      type: array
      items:
        $ref: "#/components/schemas/Aanvraag"
    Aanvraag:
      type: object
      properties:
        title:
          type: string
        about:
          type: string
        datePublished:
          $ref: "#/components/schemas/DateTime"
        dateEnd:
          $ref: "#/components/schemas/DateTime"
          nullable: true
        dateStart:
          $ref: "#/components/schemas/DateTime"
        decision:
          type: string
          nullable: true
        statusId:
          type: string
          example: besluit
          description: De statusId of the request process. Refers to the AanvraagStepStatus.id.
    AanvraagStepStatus:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        datePublished:
          $ref: "#/components/schemas/DateTime"
        documents:
          type: array
          items:
            $ref: "#/components/schemas/Document"
        productSpecific:
          type: string
          enum:
            - lening
            - uitkering
          nullable: true
          description: Only available for E-Aanvragen (Tozo, Tonk, Bbz)
        dateDecisionExpected:
          $ref: "#/components/schemas/DateTime"
          description: Only available at step herstelTermijn and inBehandeling
          nullable: true
        dateUserFeedbackExpected:
          $ref: "#/components/schemas/DateTime"
          description: Only available at step HerstelTermijn
          nullable: true
        decision:
          type: string
          description: Only available at step decision
          nullable: true
    Document:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        url:
          type: string
          example: "/wpi/document?id=95330222&isBulk=false&isDms=false"
        datePublished:
          $ref: "#/components/schemas/DateTime"
        dcteId:
          type: string
          nullable: true
    Specificatie:
      allOf:
        - $ref: "#/components/schemas/Document"
        - type: object
          properties:
            variant:
              type: string
    Date:
      type: string
      format: date
      example: "2020-06-16"
      nullable: true
    DateTime:
      type: string
      example: "2020-06-08T00:00:00"
      nullable: true
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - "ERROR"
        message:
          type: string
