import datetime


example_response = {
    "administratienummer": 9900000009,
    "bsn": 123460013,
    "fondsen": {
        "fonds": [
            {
                "besluit": "toekenning",
                "bron": "17",
                "dienstnr": 19925037,
                "dtbegin": datetime.datetime(2020, 9, 1, 0, 0),
                "dteinde": datetime.datetime(2021, 8, 31, 0, 0),
                "geldigTotEnMet": None,
                "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                "id": 180572,
                "indHoofdklant": None,
                "psonId": 9900000009,
                "recordStatus": 0,
                "refCode": {
                    "bron": "17",
                    "code": "3551",
                    "geldigTotEnMet": None,
                    "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                    "naam": "FONDS_SOORT",
                    "waardeBron": "Stadspas klant",
                    "waardeKba": "Stadspas klant",
                },
                "soortFonds": 3551,
            },
            {
                "besluit": "toekenning",
                "bron": "17",
                "dienstnr": 19925037,
                "dtbegin": datetime.datetime(2020, 9, 1, 0, 0),
                "dteinde": datetime.datetime(2021, 8, 31, 0, 0),
                "geldigTotEnMet": None,
                "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                "id": 180573,
                "indHoofdklant": None,
                "psonId": 9900000009,
                "recordStatus": 0,
                "refCode": {
                    "bron": "17",
                    "code": "3557",
                    "geldigTotEnMet": None,
                    "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                    "naam": "FONDS_SOORT",
                    "waardeBron": "Stadspas extra korting kind",
                    "waardeKba": "Aanbiedingen kind  (geeft recht op gratis ID)",
                },
                "soortFonds": 3557,
            },
        ]
    },
}


example_response2 = {
    "administratienummer": 9900000004,
    "bsn": 307741837,
    "fondsen": {
        "fonds": [
            {
                "besluit": "toekenning",
                "bron": "17",
                "dienstnr": 19939957,
                "dtbegin": datetime.datetime(2020, 9, 1, 0, 0),
                "dteinde": datetime.datetime(2021, 8, 31, 0, 0),
                "geldigTotEnMet": None,
                "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                "id": 384018,
                "indHoofdklant": "1",
                "psonId": 9900000004,
                "recordStatus": 0,
                "refCode": {
                    "bron": "17",
                    "code": "3555",
                    "geldigTotEnMet": None,
                    "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                    "naam": "FONDS_SOORT",
                    "waardeBron": "Stadspas extra korting klant",
                    "waardeKba": "Aanbiedingen klant (geeft recht op gratis ID)",
                },
                "soortFonds": 3555,
            },
            {
                "besluit": "toekenning",
                "bron": "17",
                "dienstnr": 18973167,
                "dtbegin": datetime.datetime(2018, 9, 1, 0, 0),
                "dteinde": datetime.datetime(2019, 8, 31, 0, 0),
                "geldigTotEnMet": None,
                "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                "id": 1609546,
                "indHoofdklant": "1",
                "psonId": 9900000004,
                "recordStatus": 0,
                "refCode": {
                    "bron": "17",
                    "code": "3551",
                    "geldigTotEnMet": None,
                    "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                    "naam": "FONDS_SOORT",
                    "waardeBron": "Stadspas klant",
                    "waardeKba": "Stadspas klant",
                },
                "soortFonds": 3551,
            },
            {
                "besluit": "toekenning",
                "bron": "17",
                "dienstnr": 18973167,
                "dtbegin": datetime.datetime(2018, 9, 1, 0, 0),
                "dteinde": datetime.datetime(2019, 8, 31, 0, 0),
                "geldigTotEnMet": None,
                "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                "id": 1609547,
                "indHoofdklant": "1",
                "psonId": 9900000004,
                "recordStatus": 0,
                "refCode": {
                    "bron": "17",
                    "code": "3555",
                    "geldigTotEnMet": None,
                    "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                    "naam": "FONDS_SOORT",
                    "waardeBron": "Stadspas extra korting klant",
                    "waardeKba": "Aanbiedingen klant (geeft recht op gratis ID)",
                },
                "soortFonds": 3555,
            },
            {
                "besluit": "toekenning",
                "bron": "17",
                "dienstnr": 19939957,
                "dtbegin": datetime.datetime(2020, 9, 1, 0, 0),
                "dteinde": datetime.datetime(2021, 8, 31, 0, 0),
                "geldigTotEnMet": None,
                "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                "id": 381271,
                "indHoofdklant": "1",
                "psonId": 9900000004,
                "recordStatus": 0,
                "refCode": {
                    "bron": "17",
                    "code": "3551",
                    "geldigTotEnMet": None,
                    "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                    "naam": "FONDS_SOORT",
                    "waardeBron": "Stadspas klant",
                    "waardeKba": "Stadspas klant",
                },
                "soortFonds": 3551,
            },
            {
                "besluit": "toekenning",
                "bron": "17",
                "dienstnr": 19573082,
                "dtbegin": datetime.datetime(2019, 9, 1, 0, 0),
                "dteinde": datetime.datetime(2020, 8, 31, 0, 0),
                "geldigTotEnMet": None,
                "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                "id": 740599,
                "indHoofdklant": "1",
                "psonId": 9900000004,
                "recordStatus": 0,
                "refCode": {
                    "bron": "17",
                    "code": "3551",
                    "geldigTotEnMet": None,
                    "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                    "naam": "FONDS_SOORT",
                    "waardeBron": "Stadspas klant",
                    "waardeKba": "Stadspas klant",
                },
                "soortFonds": 3551,
            },
            {
                "besluit": "toekenning",
                "bron": "17",
                "dienstnr": 19573082,
                "dtbegin": datetime.datetime(2019, 9, 1, 0, 0),
                "dteinde": datetime.datetime(2020, 8, 31, 0, 0),
                "geldigTotEnMet": None,
                "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                "id": 757447,
                "indHoofdklant": "1",
                "psonId": 9900000004,
                "recordStatus": 0,
                "refCode": {
                    "bron": "17",
                    "code": "3555",
                    "geldigTotEnMet": None,
                    "geldigVan": datetime.datetime(1900, 1, 1, 0, 0),
                    "naam": "FONDS_SOORT",
                    "waardeBron": "Stadspas extra korting klant",
                    "waardeKba": "Aanbiedingen klant (geeft recht op gratis ID)",
                },
                "soortFonds": 3555,
            },
        ]
    },
}
